version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3000:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    # ports:
    #   - '27017:27017'


# version: '3.9'

# services:
#   # MongoDB services
#   mongo_db:
#     container_name: db_container
#     image: mongo:latest
#     restart: always

#     api:
#       build: .
#       ports:
#         -3000:3000
#       environment:
#         PORT:3000

